FROM node:18-alpine AS dashboard-builder

WORKDIR /app/dashboard

COPY dashboard/package.json dashboard/package-lock.json ./
RUN npm ci

COPY dashboard ./
RUN npm run build

FROM golang:1.23-alpine

RUN apk add --no-cache git bash curl unzip entr make tar

RUN go install github.com/cespare/reflex@latest

ENV PATH="/go/bin:${PATH}"

COPY --from=dashboard-builder /app/apps/dashboard/dist /app/apps/dashboard/dist

CMD ["bash"]
